spring:
  datasource:
    driver-class-name:  oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: Oracle19
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update